name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy~=2.2.6
          pip install scikit-fuzzy~=0.5.0
          pip install scipy~=1.16.1
          pip install tqdm~=4.67.1
          pip install pytest~=8.4.2

      - name: Run tests
        run: pytest -q
